### ISSUE TITLE
ubuntu使用失败

### ISSUE THREAD

**Issue by lancer-wang** [Akegarasu/go-pixiv-proxy#2]
系统20.04.4 LTS
go-pixiv-proxy_0.2.2_linux_amd64
命令./go-pixiv-proxy -p 60025 -d xxx.xxxx.xxx
端口也开启,访问域名没有结果

**Comment by Akegarasu** [comment]
请检查域名解析是否正常
以及服务器环境是否能直连pixiv？

**Comment by lancer-wang** [comment]
> 请检查域名解析是否正常 以及服务器环境是否能直连pixiv？

服务器是外网vps可以连pixiv,
域名去ip138解析查到是有的
不知道是否和使用宝塔有关,
nginx也装了

**Comment by Akegarasu** [comment]
使用nginx需要配置反向代理该域名到你运行本程序使用的端口(60025)

**Comment by lancer-wang** [comment]
> 使用nginx需要配置反向代理该域名到你运行本程序使用的端口(60025)

不使用nginx是不是只能在本地使用?
想在其他地方调用必须得配置反向代理?

**Comment by Akegarasu** [comment]
不是 程序默认绑定的host是`127.0.0.1`，你可以使用`-h 0.0.0.0`，并且需要使用端口来访问。

**Comment by lancer-wang** [comment]
> 不是 程序默认绑定的host是`127.0.0.1`，你可以使用`-h 0.0.0.0`，并且需要使用端口来访问。

改成-h 0.0.0.0 可以了,谢谢
